// AUTO-GENERATED by Seefar from the live Supabase schema — do not edit by hand.
// Every Supabase query in this app is type-checked against the fields below.
// If the schema changes, re-run the Supabase integration to refresh this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      agents: {
        Row: {
          bio: string | null
          created_at: string | null
          id: string
          languages: string[] | null
          license: string | null
          rating: number | null
          responseTime: string | null
          reviewCount: number | null
          specializations: string[] | null
          totalListings: number | null
          userId: string
          verificationStatus: string | null
        }
        Insert: {
          bio?: string | null
          created_at?: string | null
          id?: string
          languages?: string[] | null
          license?: string | null
          rating?: number | null
          responseTime?: string | null
          reviewCount?: number | null
          specializations?: string[] | null
          totalListings?: number | null
          userId: string
          verificationStatus?: string | null
        }
        Update: {
          bio?: string | null
          created_at?: string | null
          id?: string
          languages?: string[] | null
          license?: string | null
          rating?: number | null
          responseTime?: string | null
          reviewCount?: number | null
          specializations?: string[] | null
          totalListings?: number | null
          userId?: string
          verificationStatus?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "agents_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      appointments: {
        Row: {
          agentId: string
          buyerId: string
          created_at: string | null
          id: string
          notes: string | null
          propertyId: string
          scheduledTime: string | null
          status: string | null
        }
        Insert: {
          agentId: string
          buyerId: string
          created_at?: string | null
          id?: string
          notes?: string | null
          propertyId: string
          scheduledTime?: string | null
          status?: string | null
        }
        Update: {
          agentId?: string
          buyerId?: string
          created_at?: string | null
          id?: string
          notes?: string | null
          propertyId?: string
          scheduledTime?: string | null
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "appointments_agentId_fkey"
            columns: ["agentId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_buyerId_fkey"
            columns: ["buyerId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_propertyId_fkey"
            columns: ["propertyId"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          created_at: string | null
          id: string
          participants: string[]
          propertyId: string | null
          unreadCount: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          participants: string[]
          propertyId?: string | null
          unreadCount?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          participants?: string[]
          propertyId?: string | null
          unreadCount?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_propertyId_fkey"
            columns: ["propertyId"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      favorites: {
        Row: {
          created_at: string | null
          id: string
          propertyId: string
          userId: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          propertyId: string
          userId: string
        }
        Update: {
          created_at?: string | null
          id?: string
          propertyId?: string
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorites_propertyId_fkey"
            columns: ["propertyId"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favorites_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          content: string | null
          conversationId: string
          id: string
          propertyId: string | null
          read: boolean | null
          receiverId: string
          senderId: string
          timestamp: string | null
        }
        Insert: {
          content?: string | null
          conversationId: string
          id?: string
          propertyId?: string | null
          read?: boolean | null
          receiverId: string
          senderId: string
          timestamp?: string | null
        }
        Update: {
          content?: string | null
          conversationId?: string
          id?: string
          propertyId?: string | null
          read?: boolean | null
          receiverId?: string
          senderId?: string
          timestamp?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversationId_fkey"
            columns: ["conversationId"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_propertyId_fkey"
            columns: ["propertyId"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_receiverId_fkey"
            columns: ["receiverId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_senderId_fkey"
            columns: ["senderId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      properties: {
        Row: {
          address: string | null
          agentId: string | null
          amenities: string[] | null
          area: number | null
          bathrooms: number | null
          bedrooms: number | null
          commune: string | null
          created_at: string | null
          currency: string | null
          description: string | null
          id: string
          images: string[] | null
          isVerified: boolean | null
          latitude: number | null
          longitude: number | null
          price: number | null
          status: string | null
          title: string
          type: string | null
          updated_at: string | null
          views: number | null
          wilaya: string | null
        }
        Insert: {
          address?: string | null
          agentId?: string | null
          amenities?: string[] | null
          area?: number | null
          bathrooms?: number | null
          bedrooms?: number | null
          commune?: string | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          id?: string
          images?: string[] | null
          isVerified?: boolean | null
          latitude?: number | null
          longitude?: number | null
          price?: number | null
          status?: string | null
          title: string
          type?: string | null
          updated_at?: string | null
          views?: number | null
          wilaya?: string | null
        }
        Update: {
          address?: string | null
          agentId?: string | null
          amenities?: string[] | null
          area?: number | null
          bathrooms?: number | null
          bedrooms?: number | null
          commune?: string | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          id?: string
          images?: string[] | null
          isVerified?: boolean | null
          latitude?: number | null
          longitude?: number | null
          price?: number | null
          status?: string | null
          title?: string
          type?: string | null
          updated_at?: string | null
          views?: number | null
          wilaya?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "properties_agentId_fkey"
            columns: ["agentId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      property_categories: {
        Row: {
          created_at: string | null
          icon: string | null
          id: string
          name: string
          nameAr: string | null
          nameFr: string | null
          type: string | null
        }
        Insert: {
          created_at?: string | null
          icon?: string | null
          id?: string
          name: string
          nameAr?: string | null
          nameFr?: string | null
          type?: string | null
        }
        Update: {
          created_at?: string | null
          icon?: string | null
          id?: string
          name?: string
          nameAr?: string | null
          nameFr?: string | null
          type?: string | null
        }
        Relationships: []
      }
      reviews: {
        Row: {
          agentId: string
          authorId: string
          comment: string | null
          created_at: string | null
          id: string
          rating: number | null
        }
        Insert: {
          agentId: string
          authorId: string
          comment?: string | null
          created_at?: string | null
          id?: string
          rating?: number | null
        }
        Update: {
          agentId?: string
          authorId?: string
          comment?: string | null
          created_at?: string | null
          id?: string
          rating?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_agentId_fkey"
            columns: ["agentId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_authorId_fkey"
            columns: ["authorId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      seefar_metadata: {
        Row: {
          app_id: string
          app_name: string
          created_at: string | null
          id: string
          seefar_origin: boolean | null
        }
        Insert: {
          app_id: string
          app_name: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Update: {
          app_id?: string
          app_name?: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Relationships: []
      }
      users: {
        Row: {
          bio: string | null
          created_at: string | null
          email: string | null
          id: string
          location: string | null
          name: string | null
          phone: string | null
          profileImage: string | null
          role: string | null
          updated_at: string | null
          wilaya: string | null
        }
        Insert: {
          bio?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          location?: string | null
          name?: string | null
          phone?: string | null
          profileImage?: string | null
          role?: string | null
          updated_at?: string | null
          wilaya?: string | null
        }
        Update: {
          bio?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          location?: string | null
          name?: string | null
          phone?: string | null
          profileImage?: string | null
          role?: string | null
          updated_at?: string | null
          wilaya?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
